services:
  api:
    build:
      context: ./microservices-app/api
    container_name: ms_api
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    ports:
      - "4000:4000"
    networks:
      - msnet
    restart: unless-stopped

  worker:
    build:
      context: ./microservices-app/worker
    container_name: ms_worker
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: admin
      DB_PASSWORD: admin123
      DB_NAME: mydb
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - postgres
      - redis
    networks:
      - msnet
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: ms_postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: mydb
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - msnet
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: ms_redis
    networks:
      - msnet
    restart: unless-stopped

networks:
  msnet:

volumes:
  pgdata:
